### ISSUE TITLE
`go.console.stdout` not set?

### ISSUE THREAD

**Issue by ketan** [GaneshSPatil/charts#11]

**Comment by ketan** [comment]
I suppose this is not needed for images baked by gocd, because of the entrypoint script we use, but might be needed in other cases.

**Comment by varshavaradarajan** [comment]
I think that this should be passed along as GO_AGENT_SYSTEM_PROPERTIES then.

**Comment by varshavaradarajan** [comment]
I mean that for gocd based agent images, this system property would be set. If other images are used, then the property can be passed as part of GO_AGENT_SYSTEM_PROPERTIES. So, is there any change required?
